### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by SoHiggo** [MaxCDN/php-maxcdn#4]
Hey.

Getting an error when I run a small app:

`Fatal error: Class 'MaxCDN\OAuth\OAuthConsumer' not found in M:\WWW\maxpurge\MaxCDN.php on line 25`

Is this because I am not building the app with composer. I'm a novice PHP developer. I'm not familiar with this syntax. How is a pathname a class?

**Comment by adamgrippo** [comment]
<code>MaxCDN\0Auth\0AuthConsumer</code> is a namespace not necessarily the pathname, although I'd assume the classes are being auto loaded.

What is on line 25?

**Comment by jmervine** [comment]
@SoHiggo can you confirm if this is still an open issue for you?

**Comment by SoHiggo** [comment]
It's fine, I managed to get it working in perl. I even wrote a post: http://blog.higg.im/2015/04/25/purging-assets-like-a-boss-with-the-maxcdn-api/

:)

**Comment by jmervine** [comment]
Nice!
