### ISSUE TITLE
Running without Composer

### ISSUE THREAD

**Issue by SoHiggo** [MaxCDN/php-maxcdn#5]
In the sample client, is there a way to get up and running without the reliance on composer?

**Comment by jmervine** [comment]
I'm not really a php guy, but I think if you get ext-curl installed and properly loaded it should work without composer.

**Comment by SoHiggo** [comment]
Thanks for the follow up j

I've moved away from PHP for that exact reason :) It's a cumbersome mess, and too much hackery and overhead involved.

Used Perl in the end. I'm oldskool like that

**Comment by jmervine** [comment]
@SoHiggo I'm closing this for now. Please let us know if we can help you with anything else. Cheers!
